### ISSUE TITLE
Type errors: Integers where strings belong

### ISSUE THREAD

**Issue by DrewMcN** [qe-collaborative-services/1115-hub#97] opened 2024-04-01 18:25 UTC
Please see the attached for a description of the issue. 
[Type errors - Integers where strings belong.docx](https://github.com/qe-collaborative-services/1115-hub/files/14827229/Type.errors.-.Integers.where.strings.belong.docx)

**Comment by raphaelvp** [comment] 2024-04-02 11:40
Closing this issue as this is duplicate of #98

**Closed by raphaelvp** 2024-04-02 11:40 UTC
